// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: client/compute/v1/compute_power_client.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunPythonPackageClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPythonPackageClientRequest) Reset() {
	*x = RunPythonPackageClientRequest{}
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPythonPackageClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPythonPackageClientRequest) ProtoMessage() {}

func (x *RunPythonPackageClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPythonPackageClientRequest.ProtoReflect.Descriptor instead.
func (*RunPythonPackageClientRequest) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_compute_power_client_proto_rawDescGZIP(), []int{0}
}

func (x *RunPythonPackageClientRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type RunPythonPackageClientReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecuteResult string                 `protobuf:"bytes,1,opt,name=executeResult,proto3" json:"executeResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPythonPackageClientReply) Reset() {
	*x = RunPythonPackageClientReply{}
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPythonPackageClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPythonPackageClientReply) ProtoMessage() {}

func (x *RunPythonPackageClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPythonPackageClientReply.ProtoReflect.Descriptor instead.
func (*RunPythonPackageClientReply) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_compute_power_client_proto_rawDescGZIP(), []int{1}
}

func (x *RunPythonPackageClientReply) GetExecuteResult() string {
	if x != nil {
		return x.ExecuteResult
	}
	return ""
}

type CancelExecPythonPackageClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecPythonPackageClientRequest) Reset() {
	*x = CancelExecPythonPackageClientRequest{}
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecPythonPackageClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecPythonPackageClientRequest) ProtoMessage() {}

func (x *CancelExecPythonPackageClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecPythonPackageClientRequest.ProtoReflect.Descriptor instead.
func (*CancelExecPythonPackageClientRequest) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_compute_power_client_proto_rawDescGZIP(), []int{2}
}

func (x *CancelExecPythonPackageClientRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type CancelExecPythonPackageClientReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecPythonPackageClientReply) Reset() {
	*x = CancelExecPythonPackageClientReply{}
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecPythonPackageClientReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecPythonPackageClientReply) ProtoMessage() {}

func (x *CancelExecPythonPackageClientReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_compute_power_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecPythonPackageClientReply.ProtoReflect.Descriptor instead.
func (*CancelExecPythonPackageClientReply) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_compute_power_client_proto_rawDescGZIP(), []int{3}
}

var File_client_compute_v1_compute_power_client_proto protoreflect.FileDescriptor

const file_client_compute_v1_compute_power_client_proto_rawDesc = "" +
	"\n" +
	",client/compute/v1/compute_power_client.proto\x12\x11client.compute.v1\x1a\x1cgoogle/api/annotations.proto\"1\n" +
	"\x1dRunPythonPackageClientRequest\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\"C\n" +
	"\x1bRunPythonPackageClientReply\x12$\n" +
	"\rexecuteResult\x18\x01 \x01(\tR\rexecuteResult\"8\n" +
	"$CancelExecPythonPackageClientRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"$\n" +
	"\"CancelExecPythonPackageClientReply2\xf6\x02\n" +
	"\x12ComputePowerClient\x12\xa0\x01\n" +
	"\x10RunPythonPackage\x120.client.compute.v1.RunPythonPackageClientRequest\x1a..client.compute.v1.RunPythonPackageClientReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/compute-power/client/python\x12\xbc\x01\n" +
	"\x17CancelExecPythonPackage\x127.client.compute.v1.CancelExecPythonPackageClientRequest\x1a5.client.compute.v1.CancelExecPythonPackageClientReply\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/compute-power/client/python/cancelBc\n" +
	"\x0eapi.compute.v1P\x01ZOgithub.com/tntlinking-computeshare/computeshare-client/api/client/compute/v1;v1b\x06proto3"

var (
	file_client_compute_v1_compute_power_client_proto_rawDescOnce sync.Once
	file_client_compute_v1_compute_power_client_proto_rawDescData []byte
)

func file_client_compute_v1_compute_power_client_proto_rawDescGZIP() []byte {
	file_client_compute_v1_compute_power_client_proto_rawDescOnce.Do(func() {
		file_client_compute_v1_compute_power_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_compute_v1_compute_power_client_proto_rawDesc), len(file_client_compute_v1_compute_power_client_proto_rawDesc)))
	})
	return file_client_compute_v1_compute_power_client_proto_rawDescData
}

var file_client_compute_v1_compute_power_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_client_compute_v1_compute_power_client_proto_goTypes = []any{
	(*RunPythonPackageClientRequest)(nil),        // 0: client.compute.v1.RunPythonPackageClientRequest
	(*RunPythonPackageClientReply)(nil),          // 1: client.compute.v1.RunPythonPackageClientReply
	(*CancelExecPythonPackageClientRequest)(nil), // 2: client.compute.v1.CancelExecPythonPackageClientRequest
	(*CancelExecPythonPackageClientReply)(nil),   // 3: client.compute.v1.CancelExecPythonPackageClientReply
}
var file_client_compute_v1_compute_power_client_proto_depIdxs = []int32{
	0, // 0: client.compute.v1.ComputePowerClient.RunPythonPackage:input_type -> client.compute.v1.RunPythonPackageClientRequest
	2, // 1: client.compute.v1.ComputePowerClient.CancelExecPythonPackage:input_type -> client.compute.v1.CancelExecPythonPackageClientRequest
	1, // 2: client.compute.v1.ComputePowerClient.RunPythonPackage:output_type -> client.compute.v1.RunPythonPackageClientReply
	3, // 3: client.compute.v1.ComputePowerClient.CancelExecPythonPackage:output_type -> client.compute.v1.CancelExecPythonPackageClientReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_compute_v1_compute_power_client_proto_init() }
func file_client_compute_v1_compute_power_client_proto_init() {
	if File_client_compute_v1_compute_power_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_compute_v1_compute_power_client_proto_rawDesc), len(file_client_compute_v1_compute_power_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_compute_v1_compute_power_client_proto_goTypes,
		DependencyIndexes: file_client_compute_v1_compute_power_client_proto_depIdxs,
		MessageInfos:      file_client_compute_v1_compute_power_client_proto_msgTypes,
	}.Build()
	File_client_compute_v1_compute_power_client_proto = out.File
	file_client_compute_v1_compute_power_client_proto_goTypes = nil
	file_client_compute_v1_compute_power_client_proto_depIdxs = nil
}
