// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: client/compute/v1/vm_docker.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVmDockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	BusinessId    string                 `protobuf:"bytes,4,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmDockerRequest) Reset() {
	*x = CreateVmDockerRequest{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmDockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmDockerRequest) ProtoMessage() {}

func (x *CreateVmDockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmDockerRequest.ProtoReflect.Descriptor instead.
func (*CreateVmDockerRequest) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVmDockerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateVmDockerRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *CreateVmDockerRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateVmDockerRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PrivatePort   uint32                 `protobuf:"varint,2,opt,name=private_port,json=privatePort,proto3" json:"private_port,omitempty"`
	PublicPort    uint32                 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{1}
}

func (x *PortBinding) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PortBinding) GetPrivatePort() uint32 {
	if x != nil {
		return x.PrivatePort
	}
	return 0
}

func (x *PortBinding) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *PortBinding) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteVmDockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmDockerRequest) Reset() {
	*x = DeleteVmDockerRequest{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmDockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmDockerRequest) ProtoMessage() {}

func (x *DeleteVmDockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmDockerRequest.ProtoReflect.Descriptor instead.
func (*DeleteVmDockerRequest) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteVmDockerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVmDockerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmDockerReply) Reset() {
	*x = DeleteVmDockerReply{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmDockerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmDockerReply) ProtoMessage() {}

func (x *DeleteVmDockerReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmDockerReply.ProtoReflect.Descriptor instead.
func (*DeleteVmDockerReply) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{3}
}

type GetVmDockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmDockerRequest) Reset() {
	*x = GetVmDockerRequest{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmDockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmDockerRequest) ProtoMessage() {}

func (x *GetVmDockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmDockerRequest.ProtoReflect.Descriptor instead.
func (*GetVmDockerRequest) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{4}
}

func (x *GetVmDockerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVmDockerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Ports         []*PortBinding         `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	CpuUsage      uint64                 `protobuf:"varint,4,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemoryUsage   uint64                 `protobuf:"varint,5,opt,name=memoryUsage,proto3" json:"memoryUsage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmDockerReply) Reset() {
	*x = GetVmDockerReply{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmDockerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmDockerReply) ProtoMessage() {}

func (x *GetVmDockerReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmDockerReply.ProtoReflect.Descriptor instead.
func (*GetVmDockerReply) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{5}
}

func (x *GetVmDockerReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVmDockerReply) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *GetVmDockerReply) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *GetVmDockerReply) GetCpuUsage() uint64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetVmDockerReply) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type ListVmDockerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmDockerRequest) Reset() {
	*x = ListVmDockerRequest{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmDockerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmDockerRequest) ProtoMessage() {}

func (x *ListVmDockerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmDockerRequest.ProtoReflect.Descriptor instead.
func (*ListVmDockerRequest) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{6}
}

type ListVmDockerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*GetVmDockerReply    `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmDockerReply) Reset() {
	*x = ListVmDockerReply{}
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmDockerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmDockerReply) ProtoMessage() {}

func (x *ListVmDockerReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_compute_v1_vm_docker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmDockerReply.ProtoReflect.Descriptor instead.
func (*ListVmDockerReply) Descriptor() ([]byte, []int) {
	return file_client_compute_v1_vm_docker_proto_rawDescGZIP(), []int{7}
}

func (x *ListVmDockerReply) GetResult() []*GetVmDockerReply {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_client_compute_v1_vm_docker_proto protoreflect.FileDescriptor

const file_client_compute_v1_vm_docker_proto_rawDesc = "" +
	"\n" +
	"!client/compute/v1/vm_docker.proto\x12\x11client.compute.v1\x1a\x1cgoogle/api/annotations.proto\"|\n" +
	"\x15CreateVmDockerRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x1f\n" +
	"\vbusiness_id\x18\x04 \x01(\tR\n" +
	"businessId\"u\n" +
	"\vPortBinding\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12!\n" +
	"\fprivate_port\x18\x02 \x01(\rR\vprivatePort\x12\x1f\n" +
	"\vpublic_port\x18\x03 \x01(\rR\n" +
	"publicPort\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"'\n" +
	"\x15DeleteVmDockerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteVmDockerReply\"$\n" +
	"\x12GetVmDockerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xac\x01\n" +
	"\x10GetVmDockerReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x124\n" +
	"\x05ports\x18\x03 \x03(\v2\x1e.client.compute.v1.PortBindingR\x05ports\x12\x1a\n" +
	"\bcpuUsage\x18\x04 \x01(\x04R\bcpuUsage\x12 \n" +
	"\vmemoryUsage\x18\x05 \x01(\x04R\vmemoryUsage\"\x15\n" +
	"\x13ListVmDockerRequest\"P\n" +
	"\x11ListVmDockerReply\x12;\n" +
	"\x06result\x18\x01 \x03(\v2#.client.compute.v1.GetVmDockerReplyR\x06result2\xcf\x05\n" +
	"\bVmDocker\x12s\n" +
	"\bCreateVm\x12(.client.compute.v1.CreateVmDockerRequest\x1a#.client.compute.v1.GetVmDockerReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/vm/docker\x12x\n" +
	"\bDeleteVm\x12(.client.compute.v1.DeleteVmDockerRequest\x1a&.client.compute.v1.DeleteVmDockerReply\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/vm/docker/{id}\x12o\n" +
	"\x05GetVm\x12%.client.compute.v1.GetVmDockerRequest\x1a#.client.compute.v1.GetVmDockerReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/vm/docker/{id}\x12m\n" +
	"\x06ListVm\x12&.client.compute.v1.ListVmDockerRequest\x1a$.client.compute.v1.ListVmDockerReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/vm/docker\x12z\n" +
	"\aStartVm\x12%.client.compute.v1.GetVmDockerRequest\x1a#.client.compute.v1.GetVmDockerReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/vm/docker/{id}/start\x12x\n" +
	"\x06StopVm\x12%.client.compute.v1.GetVmDockerRequest\x1a#.client.compute.v1.GetVmDockerReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/vm/docker/{id}/stopBc\n" +
	"\x0eapi.compute.v1P\x01ZOgithub.com/tntlinking-computeshare/computeshare-client/api/client/compute/v1;v1b\x06proto3"

var (
	file_client_compute_v1_vm_docker_proto_rawDescOnce sync.Once
	file_client_compute_v1_vm_docker_proto_rawDescData []byte
)

func file_client_compute_v1_vm_docker_proto_rawDescGZIP() []byte {
	file_client_compute_v1_vm_docker_proto_rawDescOnce.Do(func() {
		file_client_compute_v1_vm_docker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_compute_v1_vm_docker_proto_rawDesc), len(file_client_compute_v1_vm_docker_proto_rawDesc)))
	})
	return file_client_compute_v1_vm_docker_proto_rawDescData
}

var file_client_compute_v1_vm_docker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_client_compute_v1_vm_docker_proto_goTypes = []any{
	(*CreateVmDockerRequest)(nil), // 0: client.compute.v1.CreateVmDockerRequest
	(*PortBinding)(nil),           // 1: client.compute.v1.PortBinding
	(*DeleteVmDockerRequest)(nil), // 2: client.compute.v1.DeleteVmDockerRequest
	(*DeleteVmDockerReply)(nil),   // 3: client.compute.v1.DeleteVmDockerReply
	(*GetVmDockerRequest)(nil),    // 4: client.compute.v1.GetVmDockerRequest
	(*GetVmDockerReply)(nil),      // 5: client.compute.v1.GetVmDockerReply
	(*ListVmDockerRequest)(nil),   // 6: client.compute.v1.ListVmDockerRequest
	(*ListVmDockerReply)(nil),     // 7: client.compute.v1.ListVmDockerReply
}
var file_client_compute_v1_vm_docker_proto_depIdxs = []int32{
	1, // 0: client.compute.v1.GetVmDockerReply.ports:type_name -> client.compute.v1.PortBinding
	5, // 1: client.compute.v1.ListVmDockerReply.result:type_name -> client.compute.v1.GetVmDockerReply
	0, // 2: client.compute.v1.VmDocker.CreateVm:input_type -> client.compute.v1.CreateVmDockerRequest
	2, // 3: client.compute.v1.VmDocker.DeleteVm:input_type -> client.compute.v1.DeleteVmDockerRequest
	4, // 4: client.compute.v1.VmDocker.GetVm:input_type -> client.compute.v1.GetVmDockerRequest
	6, // 5: client.compute.v1.VmDocker.ListVm:input_type -> client.compute.v1.ListVmDockerRequest
	4, // 6: client.compute.v1.VmDocker.StartVm:input_type -> client.compute.v1.GetVmDockerRequest
	4, // 7: client.compute.v1.VmDocker.StopVm:input_type -> client.compute.v1.GetVmDockerRequest
	5, // 8: client.compute.v1.VmDocker.CreateVm:output_type -> client.compute.v1.GetVmDockerReply
	3, // 9: client.compute.v1.VmDocker.DeleteVm:output_type -> client.compute.v1.DeleteVmDockerReply
	5, // 10: client.compute.v1.VmDocker.GetVm:output_type -> client.compute.v1.GetVmDockerReply
	7, // 11: client.compute.v1.VmDocker.ListVm:output_type -> client.compute.v1.ListVmDockerReply
	5, // 12: client.compute.v1.VmDocker.StartVm:output_type -> client.compute.v1.GetVmDockerReply
	5, // 13: client.compute.v1.VmDocker.StopVm:output_type -> client.compute.v1.GetVmDockerReply
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_compute_v1_vm_docker_proto_init() }
func file_client_compute_v1_vm_docker_proto_init() {
	if File_client_compute_v1_vm_docker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_compute_v1_vm_docker_proto_rawDesc), len(file_client_compute_v1_vm_docker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_compute_v1_vm_docker_proto_goTypes,
		DependencyIndexes: file_client_compute_v1_vm_docker_proto_depIdxs,
		MessageInfos:      file_client_compute_v1_vm_docker_proto_msgTypes,
	}.Build()
	File_client_compute_v1_vm_docker_proto = out.File
	file_client_compute_v1_vm_docker_proto_goTypes = nil
	file_client_compute_v1_vm_docker_proto_depIdxs = nil
}
