// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: client/network/v1/p2p.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	TargetAddress string                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenRequest) Reset() {
	*x = CreateListenRequest{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenRequest) ProtoMessage() {}

func (x *CreateListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenRequest.ProtoReflect.Descriptor instead.
func (*CreateListenRequest) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListenRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CreateListenRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type CreateListenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenReply) Reset() {
	*x = CreateListenReply{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenReply) ProtoMessage() {}

func (x *CreateListenReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenReply.ProtoReflect.Descriptor instead.
func (*CreateListenReply) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{1}
}

type CreateForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Portal        string                 `protobuf:"bytes,1,opt,name=portal,proto3" json:"portal,omitempty"`
	ListenAddress string                 `protobuf:"bytes,2,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForwardRequest) Reset() {
	*x = CreateForwardRequest{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForwardRequest) ProtoMessage() {}

func (x *CreateForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForwardRequest.ProtoReflect.Descriptor instead.
func (*CreateForwardRequest) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *CreateForwardRequest) GetPortal() string {
	if x != nil {
		return x.Portal
	}
	return ""
}

func (x *CreateForwardRequest) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *CreateForwardRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type CreateForwardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForwardReply) Reset() {
	*x = CreateForwardReply{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForwardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForwardReply) ProtoMessage() {}

func (x *CreateForwardReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForwardReply.ProtoReflect.Descriptor instead.
func (*CreateForwardReply) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{3}
}

type CloseListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ListenAddress string                 `protobuf:"bytes,2,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseListenRequest) Reset() {
	*x = CloseListenRequest{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseListenRequest) ProtoMessage() {}

func (x *CloseListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseListenRequest.ProtoReflect.Descriptor instead.
func (*CloseListenRequest) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *CloseListenRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CloseListenRequest) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *CloseListenRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type CloseListenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseListenReply) Reset() {
	*x = CloseListenReply{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseListenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseListenReply) ProtoMessage() {}

func (x *CloseListenReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseListenReply.ProtoReflect.Descriptor instead.
func (*CloseListenReply) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{5}
}

type ListenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ListenAddress string                 `protobuf:"bytes,2,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"`
	TargetAddress string                 `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenReply) Reset() {
	*x = ListenReply{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenReply) ProtoMessage() {}

func (x *ListenReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenReply.ProtoReflect.Descriptor instead.
func (*ListenReply) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *ListenReply) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListenReply) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *ListenReply) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type ListListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListenRequest) Reset() {
	*x = ListListenRequest{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListenRequest) ProtoMessage() {}

func (x *ListListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListenRequest.ProtoReflect.Descriptor instead.
func (*ListListenRequest) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{7}
}

type ListListenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*ListenReply         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListenReply) Reset() {
	*x = ListListenReply{}
	mi := &file_client_network_v1_p2p_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListenReply) ProtoMessage() {}

func (x *ListListenReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_network_v1_p2p_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListenReply.ProtoReflect.Descriptor instead.
func (*ListListenReply) Descriptor() ([]byte, []int) {
	return file_client_network_v1_p2p_proto_rawDescGZIP(), []int{8}
}

func (x *ListListenReply) GetResult() []*ListenReply {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_client_network_v1_p2p_proto protoreflect.FileDescriptor

const file_client_network_v1_p2p_proto_rawDesc = "" +
	"\n" +
	"\x1bclient/network/v1/p2p.proto\x12\x11client.network.v1\x1a\x1cgoogle/api/annotations.proto\"X\n" +
	"\x13CreateListenRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\tR\rtargetAddress\"\x13\n" +
	"\x11CreateListenReply\"|\n" +
	"\x14CreateForwardRequest\x12\x16\n" +
	"\x06portal\x18\x01 \x01(\tR\x06portal\x12%\n" +
	"\x0elisten_address\x18\x02 \x01(\tR\rlistenAddress\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\"\x14\n" +
	"\x12CreateForwardReply\"~\n" +
	"\x12CloseListenRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12%\n" +
	"\x0elisten_address\x18\x02 \x01(\tR\rlistenAddress\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\"\x12\n" +
	"\x10CloseListenReply\"w\n" +
	"\vListenReply\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12%\n" +
	"\x0elisten_address\x18\x02 \x01(\tR\rlistenAddress\x12%\n" +
	"\x0etarget_address\x18\x03 \x01(\tR\rtargetAddress\"\x13\n" +
	"\x11ListListenRequest\"I\n" +
	"\x0fListListenReply\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.client.network.v1.ListenReplyR\x06result2\xdc\x03\n" +
	"\x03P2p\x12w\n" +
	"\fCreateListen\x12&.client.network.v1.CreateListenRequest\x1a$.client.network.v1.CreateListenReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/p2p/listen\x12{\n" +
	"\rCreateForward\x12'.client.network.v1.CreateForwardRequest\x1a%.client.network.v1.CreateForwardReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/p2p/forward\x12s\n" +
	"\vCloseListen\x12%.client.network.v1.CloseListenRequest\x1a#.client.network.v1.CloseListenReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/p2p/close\x12j\n" +
	"\n" +
	"ListListen\x12$.client.network.v1.ListListenRequest\x1a\".client.network.v1.ListListenReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/p2p/lsBV\n" +
	"\x0eapi.network.v1P\x01ZBgithub.com/tntlinking-computeshare/computeshare-client/api/client/network/v1;v1b\x06proto3"

var (
	file_client_network_v1_p2p_proto_rawDescOnce sync.Once
	file_client_network_v1_p2p_proto_rawDescData []byte
)

func file_client_network_v1_p2p_proto_rawDescGZIP() []byte {
	file_client_network_v1_p2p_proto_rawDescOnce.Do(func() {
		file_client_network_v1_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_network_v1_p2p_proto_rawDesc), len(file_client_network_v1_p2p_proto_rawDesc)))
	})
	return file_client_network_v1_p2p_proto_rawDescData
}

var file_client_network_v1_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_client_network_v1_p2p_proto_goTypes = []any{
	(*CreateListenRequest)(nil),  // 0: client.network.v1.CreateListenRequest
	(*CreateListenReply)(nil),    // 1: client.network.v1.CreateListenReply
	(*CreateForwardRequest)(nil), // 2: client.network.v1.CreateForwardRequest
	(*CreateForwardReply)(nil),   // 3: client.network.v1.CreateForwardReply
	(*CloseListenRequest)(nil),   // 4: client.network.v1.CloseListenRequest
	(*CloseListenReply)(nil),     // 5: client.network.v1.CloseListenReply
	(*ListenReply)(nil),          // 6: client.network.v1.ListenReply
	(*ListListenRequest)(nil),    // 7: client.network.v1.ListListenRequest
	(*ListListenReply)(nil),      // 8: client.network.v1.ListListenReply
}
var file_client_network_v1_p2p_proto_depIdxs = []int32{
	6, // 0: client.network.v1.ListListenReply.result:type_name -> client.network.v1.ListenReply
	0, // 1: client.network.v1.P2p.CreateListen:input_type -> client.network.v1.CreateListenRequest
	2, // 2: client.network.v1.P2p.CreateForward:input_type -> client.network.v1.CreateForwardRequest
	4, // 3: client.network.v1.P2p.CloseListen:input_type -> client.network.v1.CloseListenRequest
	7, // 4: client.network.v1.P2p.ListListen:input_type -> client.network.v1.ListListenRequest
	1, // 5: client.network.v1.P2p.CreateListen:output_type -> client.network.v1.CreateListenReply
	3, // 6: client.network.v1.P2p.CreateForward:output_type -> client.network.v1.CreateForwardReply
	5, // 7: client.network.v1.P2p.CloseListen:output_type -> client.network.v1.CloseListenReply
	8, // 8: client.network.v1.P2p.ListListen:output_type -> client.network.v1.ListListenReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_network_v1_p2p_proto_init() }
func file_client_network_v1_p2p_proto_init() {
	if File_client_network_v1_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_network_v1_p2p_proto_rawDesc), len(file_client_network_v1_p2p_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_network_v1_p2p_proto_goTypes,
		DependencyIndexes: file_client_network_v1_p2p_proto_depIdxs,
		MessageInfos:      file_client_network_v1_p2p_proto_msgTypes,
	}.Build()
	File_client_network_v1_p2p_proto = out.File
	file_client_network_v1_p2p_proto_goTypes = nil
	file_client_network_v1_p2p_proto_depIdxs = nil
}
