// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: client/system/v1/agent_register.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_client_system_v1_agent_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_system_v1_agent_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_client_system_v1_agent_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_client_system_v1_agent_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_system_v1_agent_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_client_system_v1_agent_register_proto_rawDescGZIP(), []int{1}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_client_system_v1_agent_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_system_v1_agent_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_client_system_v1_agent_register_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_client_system_v1_agent_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_system_v1_agent_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_client_system_v1_agent_register_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatReply) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeartbeatReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UnRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnRegisterRequest) Reset() {
	*x = UnRegisterRequest{}
	mi := &file_client_system_v1_agent_register_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterRequest) ProtoMessage() {}

func (x *UnRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_system_v1_agent_register_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterRequest.ProtoReflect.Descriptor instead.
func (*UnRegisterRequest) Descriptor() ([]byte, []int) {
	return file_client_system_v1_agent_register_proto_rawDescGZIP(), []int{4}
}

func (x *UnRegisterRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type UnRegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnRegisterReply) Reset() {
	*x = UnRegisterReply{}
	mi := &file_client_system_v1_agent_register_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterReply) ProtoMessage() {}

func (x *UnRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_client_system_v1_agent_register_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterReply.ProtoReflect.Descriptor instead.
func (*UnRegisterReply) Descriptor() ([]byte, []int) {
	return file_client_system_v1_agent_register_proto_rawDescGZIP(), []int{5}
}

var File_client_system_v1_agent_register_proto protoreflect.FileDescriptor

const file_client_system_v1_agent_register_proto_rawDesc = "" +
	"\n" +
	"%client/system/v1/agent_register.proto\x12\x14api.client.system.v1\x1a\x1cgoogle/api/annotations.proto\"*\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\x0f\n" +
	"\rRegisterReply\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"6\n" +
	"\x0eHeartbeatReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\",\n" +
	"\x11UnRegisterRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\x11\n" +
	"\x0fUnRegisterReply2\xb1\x02\n" +
	"\rAgentRegister\x12V\n" +
	"\bRegister\x12%.api.client.system.v1.RegisterRequest\x1a#.api.client.system.v1.RegisterReply\x12j\n" +
	"\tHeartbeat\x12&.api.client.system.v1.HeartbeatRequest\x1a$.api.client.system.v1.HeartbeatReply\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/health\x12\\\n" +
	"\n" +
	"UnRegister\x12'.api.client.system.v1.UnRegisterRequest\x1a%.api.client.system.v1.UnRegisterReplyBT\n" +
	"\rapi.system.v1P\x01ZAgithub.com/mohaijiang/computeshare-client/api/client/system/v1;v1b\x06proto3"

var (
	file_client_system_v1_agent_register_proto_rawDescOnce sync.Once
	file_client_system_v1_agent_register_proto_rawDescData []byte
)

func file_client_system_v1_agent_register_proto_rawDescGZIP() []byte {
	file_client_system_v1_agent_register_proto_rawDescOnce.Do(func() {
		file_client_system_v1_agent_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_system_v1_agent_register_proto_rawDesc), len(file_client_system_v1_agent_register_proto_rawDesc)))
	})
	return file_client_system_v1_agent_register_proto_rawDescData
}

var file_client_system_v1_agent_register_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_client_system_v1_agent_register_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: api.client.system.v1.RegisterRequest
	(*RegisterReply)(nil),     // 1: api.client.system.v1.RegisterReply
	(*HeartbeatRequest)(nil),  // 2: api.client.system.v1.HeartbeatRequest
	(*HeartbeatReply)(nil),    // 3: api.client.system.v1.HeartbeatReply
	(*UnRegisterRequest)(nil), // 4: api.client.system.v1.UnRegisterRequest
	(*UnRegisterReply)(nil),   // 5: api.client.system.v1.UnRegisterReply
}
var file_client_system_v1_agent_register_proto_depIdxs = []int32{
	0, // 0: api.client.system.v1.AgentRegister.Register:input_type -> api.client.system.v1.RegisterRequest
	2, // 1: api.client.system.v1.AgentRegister.Heartbeat:input_type -> api.client.system.v1.HeartbeatRequest
	4, // 2: api.client.system.v1.AgentRegister.UnRegister:input_type -> api.client.system.v1.UnRegisterRequest
	1, // 3: api.client.system.v1.AgentRegister.Register:output_type -> api.client.system.v1.RegisterReply
	3, // 4: api.client.system.v1.AgentRegister.Heartbeat:output_type -> api.client.system.v1.HeartbeatReply
	5, // 5: api.client.system.v1.AgentRegister.UnRegister:output_type -> api.client.system.v1.UnRegisterReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_system_v1_agent_register_proto_init() }
func file_client_system_v1_agent_register_proto_init() {
	if File_client_system_v1_agent_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_system_v1_agent_register_proto_rawDesc), len(file_client_system_v1_agent_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_system_v1_agent_register_proto_goTypes,
		DependencyIndexes: file_client_system_v1_agent_register_proto_depIdxs,
		MessageInfos:      file_client_system_v1_agent_register_proto_msgTypes,
	}.Build()
	File_client_system_v1_agent_register_proto = out.File
	file_client_system_v1_agent_register_proto_goTypes = nil
	file_client_system_v1_agent_register_proto_depIdxs = nil
}
